cc_library(
    name = "assfire_router_cc_api",
    srcs = [
        "assfire/router/api/Api.cpp",
    ],
    hdrs = [
        "assfire/router/api/GeoPoint.hpp",
        "assfire/router/api/Route.hpp",
        "assfire/router/api/RouteInfo.hpp",
        "assfire/router/api/RouteMatrix.hpp",
        "assfire/router/api/RoutesProvider.hpp",
        "assfire/router/api/RoutingStrategyId.hpp",
        "assfire/router/api/TransportProfileId.hpp",
    ],
    include_prefix = "assfire/router/api",
    strip_include_prefix = "assfire/router/api",
    visibility = ["//visibility:public"],
    copts = ["/std:c++20"]
)
